.\"        Title: openrpg
.\"       Author: [see the "Authors" section]
.\"         Date: 01/13/2020
.\"     Language: English

.\" View this man page with the command
.\" man -l openrpg-roll.1
.\" When installing, gzip this file and place it in the man folder

.\" For information on macros used in this file, see man page
.\" groff_man(7)
.\" http://man7.org/linux/man-pages/man7/groff_man.7.html

.\" Header and footer information
.TH "OPENRPG-ROLL" "1" "2020-01-13" "OPENRPG" "OpenRPG Manual"

.\" NAME section
.\" TODO: Redo this text
.SH "NAME"
openrpg\-roll \- emulates the rolling of variable\-sized dice

.\" SYNOPSIS section, includes basic command form
.SH "SYNOPSIS"
.B roll
[\fI\,OPTION\/\fR]... \fI\,XdY\/\fR [+|\- AdB]... [+|\- N]...

.\" DESCRIPTION section, includes command line arguments
.SH "DESCRIPTION"
.PP
.\" TODO: redo this text
Roll allows the user to roll any number, X, of dice with any number of sides, Y, and provides support for dice and integer arithmetic

.SS "OPTIONS"
.TP
\fB\-h\fR, \fB\-\-help\fR
displays the help message and exits
.TP
\fB\-v\fR, \fB\-\-verbose\fR
supresses quiet flag and sets verbose flag
.TP
\fB\-V\fR, \fB\-\-version\fR
print version info

.SH "COPYRIGHT"
.\" TODO copyright text
.\" What's the proper copyright text? For now I'm just putting the license
OpenRPG Software License \- Version 1.0 \- February 10th, 2017 \fB\fI\,https://openrpg.io/about/license/\/\fR